// ** Icons Import
import {
  Shield,
  CreditCard,
  Users,
  Image,
  PenTool,
  Award,
  MessageSquare,
  Settings,
  MessageCircle,
  Server,
  Percent,
  FileText,
  Grid,
  PhoneCall,
  Globe,
  BookOpen,
  Calendar,
  Box,
  Home,
} from "react-feather";

export default [
  {
    header: "Apps & Pages",
  },
  {
    id: "roles-permissions",
    title: "Roles & Permissions",
    icon: <Shield size={20} />,
    navLink: "/apps/roles",
    resource: "read-roles",
  },
  {
    id: "user-categories",
    title: "User Categories",
    icon: <Server size={20} />,
    navLink: "/apps/categories/user",
    resource: "read-categories",
  },
  {
    id: "users",
    title: "Users",
    icon: <Users size={20} />,
    navLink: "/apps/user/list/all",
    resource: "read-users",
  },
  {
    header: "Sites",
  },
  {
    id: "site-categories",
    title: "Site Categories",
    icon: <Server size={20} />,
    navLink: "/apps/categories/site",
    resource: "read-categories",
  },
  {
    id: "sites",
    title: "Sites",
    icon: <Globe size={20} />,
    navLink: "/apps/site",
  },
  {
    id: "event-categories",
    title: "Event Categories",
    icon: <Server size={20} />,
    navLink: "/apps/categories/event",
  },
  {
    id: "events",
    title: "Events",
    icon: <Calendar size={20} />,
    navLink: "/apps/events",
  },
  {
    id: "services",
    title: "Services",
    icon: <Box size={20} />,
    navLink: "/apps/services",
  },
  {
    id: "halls",
    title: "Halls",
    icon: <Home size={20} />,
    navLink: "/apps/halls",
  },
  {
    id: "lecturers",
    title: "Lecturer",
    icon: <Users size={20} />,
    navLink: "/apps/user/list/lecturer",
  },
  {
    id: "workshops",
    title: "Workshops",
    icon: <BookOpen size={20} />,
    navLink: "/apps/workshops",
  },
  {
    id: "seminars",
    title: "Seminars",
    icon: <BookOpen size={20} />,
    navLink: "/apps/seminars",
  },
  {
    header: "Content",
  },
  {
    id: "blog-categories",
    title: "Blog Categories",
    icon: <Server size={20} />,
    navLink: "/apps/categories/blog",
  },
  {
    id: "blog",
    title: "Blog",
    icon: <PenTool size={20} />,
    navLink: "/apps/blogs",
  },
  {
    id: "comments",
    title: "Comments",
    icon: <MessageCircle size={20} />,
    navLink: "/apps/comments",
  },
  {
    header: "Support",
  },
  {
    id: "departments",
    title: "Departments",
    icon: <Grid size={20} />,
    navLink: "/apps/departments",
  },
  {
    id: "chats",
    title: "Chats",
    icon: <MessageSquare size={20} />,
    navLink: "/apps/ticket",
    badge: "light-danger",
    badgeText: "2",
  },
  {
    header: "Features",
  },
  {
    id: "shop-slider",
    title: "Sliders",
    icon: <Image size={20} />,
    navLink: "/apps/sliders",
  },
  {
    id: "brands",
    title: "Brands",
    icon: <Award size={20} />,
    navLink: "/apps/brands",
  },
  {
    id: "coupons",
    title: "Coupons",
    icon: <Percent size={20} />,
    navLink: "/apps/coupons/course",
  },
  {
    id: "invoices",
    title: "Invoices",
    icon: <FileText size={20} />,
    navLink: "/apps/invoices",
  },
  {
    header: "Financial",
  },
  {
    id: "payments",
    title: "Payments",
    icon: <CreditCard size={20} />,
    navLink: "/apps/payments",
  },
  {
    header: "Setting",
  },
  {
    id: "contact",
    title: "Contacts",
    icon: <PhoneCall size={20} />,
    navLink: "/apps/contacts",
  },
  {
    id: "setting",
    title: "Setting",
    icon: <Settings size={20} />,
    navLink: "/apps/setting",
  },
];
